name: Deploy Continuo para o Raspberry Pi

on:
  push:
    branches:
      - main # Executa sempre que subir código para a branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar Deploy via SSH no Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Carrega o NVM se usar, ou garante acesso aos binários do Node no path do Pi
            
            cd ~/apps/meu-portfolio
            
            echo "📥 Atualizando código fonte..."
            git pull origin main
            
            echo "📦 Instalando dependências..."
            npm install --omit=dev # --omit=dev economiza memória no Raspberry Pi 3
            
            echo "🔄 Sincronizando schema do banco..."
            npx prisma generate
            npm run db:push
            
            echo "🏗️ Gerando nova compilação da aplicação..."
            npm run build
            
            echo "🚀 Reiniciando servidor no PM2..."
            pm2 restart "aura-portfolio"
            
            echo "✅ Deploy finalizado com sucesso!"
